name: Hardhat Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Hardhat Docker image
        run: |
          docker build -f Dockerfile.hardhat -t ${{ secrets.DOCKER_USERNAME }}/hardhat:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hardhat:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/hardhat:latest
            docker stop hardhat || true
            docker rm hardhat || true
            docker run --rm --network host --name hardhat ${{ secrets.DOCKER_USERNAME }}/hardhat:latest
